import { Question } from '../../utils';

export const questions: Question[] = [
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'medium',
    question: 'Nintendo started out as a playing card manufacturer.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, went bankrupt on March 1st, 2010.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'DragonForces Through the Fire and Flames is widely considered to be the hardest song in the Guitar Hero series.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'History',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'The two atomic bombs dropped on Japan by the United States in August 1945 were named Little Man and Fat Boy.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Science: Computers',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Vehicles',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'The Japanese Shinkansen beat the French TGVs speed record for fastest electric rail train.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Science: Mathematics',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'The proof for the Chinese Remainder Theorem used in Number Theory was NOT developed by its first publisher, Sun Tzu.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Animals',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'Kamea, the Gilbertese Islander word for dog, is derived from the English phrase Come here!',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'medium',
    question: 'Furby was released in 1998.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'medium',
    question: 'There are 86400 seconds in a day.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Science: Mathematics',
    type: 'boolean',
    difficulty: 'easy',
    question: 'The Squaring the Circle problem is solvable.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Science: Computers',
    type: 'boolean',
    difficulty: 'medium',
    question: 'Windows NT is a monolithic kernel.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'The bikini is named after the Bikini Atoll, an island where the United States conducted tests on atomic bombs.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Japanese Anime & Manga',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'In Kill La Kill, the weapon of the main protagonist is a katana. ',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'easy',
    question: 'The Sun rises from the North.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'easy',
    question: 'You can legally drink alcohol while driving in Mississippi.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'In Half-Life 2, if you play the zombies speech in reverse, they actually speak coherent English.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Board Games',
    type: 'boolean',
    difficulty: 'easy',
    question: 'The Angry Video Game Nerds alter ego is Board James.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'hard',
    question:
      'TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'TF2: The Heavys voice actor, Gary Schwartz, voices the Demoman as well ',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Science & Nature',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'Centripedal force is an apparent force that acts outward on a body moving around a center, arising from the bodys inertia.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Science: Computers',
    type: 'boolean',
    difficulty: 'hard',
    question: 'DHCP stands for Dynamic Host Configuration Port.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question: 'In the game Subnautica, a Spadefish will attack you.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'medium',
    question: 'In the game Subnautica, a Cave Crawler will attack you.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Science: Gadgets',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'Microphones can be used not only to pick up sound, but also to project sound similar to a speaker.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Science: Computers',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'In Pok&eacute;mon Sun and Moon, a male Salandit can evolve to a Salazzle.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'easy',
    question: 'A Saxophone is a brass instrument.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'hard',
    question: 'The band STRFKR was also briefly known as Pyramiddd.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Mythology',
    type: 'boolean',
    difficulty: 'easy',
    question: 'According to Greek Mythology, Atlas was an Olympian God.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'For his performance at ComplexCon 2016 in Long Beach, California, Skrillex revived his Mothership set piece for one night only.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Science: Mathematics',
    type: 'boolean',
    difficulty: 'medium',
    question: 'E = MC3',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Japanese Anime & Manga',
    type: 'boolean',
    difficulty: 'hard',
    question: 'Druid is a mage class in Log Horizon.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'History',
    type: 'boolean',
    difficulty: 'easy',
    question: 'Kublai Khan is the grandchild of Genghis Khan?',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Television',
    type: 'boolean',
    difficulty: 'hard',
    question: 'The Klingon home planet is QonoS.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Television',
    type: 'boolean',
    difficulty: 'easy',
    question: 'In Star Trek, Klaang is a typical Klingon male.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Board Games',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'Rich Uncle Pennybags from the board game Monopoly wears a monocle.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'hard',
    question:
      'Pete Townshends solo album, White City: A Novel, is set in the metropolitan area of Chicago.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'In League of Legends, there exists four different types of Dragon.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Video Games',
    type: 'boolean',
    difficulty: 'easy',
    question: 'The game Pocket Morty has a Morty called Pocket Mortys Morty?',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Geography',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'New Haven is the capital city of the state of Connecticut in the United States.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Music',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'Musical artist, Future, collaborated with Kendrick Lamar for the song: Mask Off.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'History',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'The United States of America was the first country to launch a man into space.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Vehicles',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'BMW M GmbH is a subsidiary of BMW AG that focuses on car performance.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Animals',
    type: 'boolean',
    difficulty: 'medium',
    question: 'Tigers have one colour of skin despite the stripey fur.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Geography',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'There is an island in Japan called \u014ckunoshima, A.K.A. Rabbit Island, so named because of its huge population of rabbits.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'easy',
    question:
      'Vietnams national flag is a red star in front of a yellow background.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'General Knowledge',
    type: 'boolean',
    difficulty: 'easy',
    question: 'A pasodoble is a type of Italian pasta sauce.',
    correct_answer: 'False',
    incorrect_answer: 'True',
  },
  {
    category: 'Entertainment: Japanese Anime & Manga',
    type: 'boolean',
    difficulty: 'medium',
    question:
      'In Full Metal Panic!, Whispered are those who are capable of creating Black Technology.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
  {
    category: 'Entertainment: Musicals & Theatres',
    type: 'boolean',
    difficulty: 'hard',
    question:
      'The protagonists names in Whos Afraid of Virginia Woolf, George and Martha, were derived from George Washington and his wife.',
    correct_answer: 'True',
    incorrect_answer: 'False',
  },
];
